// Generated by CoffeeScript 1.6.3
(function() {
  define(['dropbox'], function(Dropbox) {
    var auth, client, key;
    client = new Dropbox.Client({
      key: 'bU8mb6wQpnA=|yAAb6C7Ke3/ROsEP06RqVJrxDez/09agnys6gI10Ag==',
      sandbox: true
    });
    auth = function() {
      if (client.isAuthenticated()) {
        alert('Already connected to Dropbox.');
        return;
      }
      client.authDriver(new Dropbox.Drivers.Redirect({
        rememberUser: true
      }));
      return client.authenticate(function(error, authed_client) {
        if (error) {
          alert("Error: could not connect to Dropbox.");
          console.log(error);
          return;
        }
        return authed_client.getUserInfo(function(error, info) {
          return console.log(info.name);
        });
      });
    };
    for (key in localStorage) {
      if (key.indexOf('dropbox-auth') !== -1) {
        auth();
        break;
      }
    }
    return {
      client: client,
      auth: auth
    };
  });

}).call(this);
