// Generated by CoffeeScript 1.6.3
(function() {
  var deps;

  requirejs.config({
    paths: {
      highlight: 'res/highlight/build/highlight.pack',
      jquery: 'res/jquery',
      backbone: 'res/backbone',
      marked: 'res/marked',
      dropbox: 'res/dropbox',
      underscore: 'res/underscore',
      modal: 'js/modal',
      client: 'js/client',
      toolbar: 'js/toolbar',
      editor: 'js/editor'
    },
    shim: {
      dropbox: {
        exports: 'Dropbox'
      },
      jquery: {
        exports: '$'
      },
      underscore: {
        exports: '_'
      },
      backbone: {
        exports: 'Backbone',
        deps: ['jquery', 'underscore']
      }
    }
  });

  deps = ['jquery', 'backbone', 'marked', 'highlight', 'dropbox', 'modal', 'client', 'toolbar', 'editor'];

  require(deps, function($, Backbone, marked, hl, Dropbox, modal, client, Toolbar, editor) {
    var File, FileList, Modal, auth, update, _ref, _ref1;
    Modal = modal.Modal, File = modal.File, FileList = modal.FileList;
    _ref = client, client = _ref.client, auth = _ref.auth;
    _ref1 = editor, editor = _ref1.editor, update = _ref1.update;
    window.dom = {};
    (function($) {
      return $.fn.centre = function() {
        this.css({
          left: (dom.window.width() - this.width()) / 2
        });
        return this;
      };
    })(jQuery);
    window.alert = function(text) {
      return dom.message.text(text).centre().fadeIn('fast').delay(2000).fadeOut('slow');
    };
    marked.setOptions({
      smartypants: true,
      breaks: true,
      sanitize: true,
      smartLists: true,
      highlight: function(code, lang) {
        return hl.highlightAuto(code).value;
      }
    });
    return $(document).ready(function() {
      var list, s, toolbar, _i, _len, _ref2;
      list = new FileList([
        {
          name: 'test'
        }
      ]);
      modal = new Modal({
        model: list
      });
      modal.$el.appendTo('body');
      modal.render();
      toolbar = new Toolbar();
      toolbar.$el.appendTo('header > .right');
      toolbar.render();
      _ref2 = ['viewer', 'dropbox', 'open', 'save', 'message', 'modal', 'save-message', 'filename'];
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        s = _ref2[_i];
        dom[s.replace('-', '_')] = $('#' + s);
      }
      dom.window = $(window);
      dom.shade = $('.shade');
      $.get('sample.md', function(text) {
        return editor.setValue(text);
      });
      return update();
    });
  });

}).call(this);
