// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'underscore', 'backbone', 'client'], function($, _, Backbone, client) {
    var File, FileList, Modal;
    client = client.client;
    File = Backbone.Model.extend({
      defaults: {
        name: ''
      }
    });
    FileList = Backbone.Collection.extend({
      model: File
    });
    Modal = Backbone.View.extend({
      id: 'modal',
      events: {
        'click .close': 'close'
      },
      template: _.template(JST.modal),
      initialize: function() {},
      close: function() {
        return this.$el.fadeOut('fast');
      },
      render: function() {
        this.$el.html(this.template({
          entries: this.model.toJSON()
        }));
        return this;
      }
    });
    return {
      Modal: Modal,
      File: File,
      FileList: FileList
    };
  });

}).call(this);
