// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone', 'modal'], function(Backbone, modal) {
    var Modal, SettingsPanel, SettingsView;
    Modal = modal.Modal;
    SettingsPanel = Backbone.View.extend({
      template: _.template(JST.settings)
    });
    SettingsView = Modal.extend();
    return SettingsView;
  });

}).call(this);
