// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore', 'backbone', 'client', 'editor'], function(_, Backbone, client, editor) {
    var Toolbar, auth, _ref;
    _ref = client, client = _ref.client, auth = _ref.auth;
    editor = editor.editor;
    return Toolbar = Backbone.View.extend({
      tagName: 'nav',
      events: {
        'click #dropbox': 'connect',
        'click #open': 'open',
        'click #save': 'save',
        'click #export': 'export',
        'click #settings': 'settings'
      },
      render: function() {
        this.$el.html(JST.toolbar);
        return this;
      },
      connect: function() {
        return auth();
      },
      open: function() {
        dom.shade.show();
        return dom.modal.centre().fadeIn('fast');
      },
      save: function() {
        var filename;
        if (client == null) {
          alert('Please connect to Dropbox to save documents.');
          return;
        }
        filename = dom.filename.val();
        if (!filename) {
          alert('Please name this document before saving.');
          return;
        }
        filename += '.md';
        return client.writeFile(filename, editor.getValue(), function(error, stat) {
          if (error) {
            alert('Error: could not save file.');
            console.log(error);
            return;
          }
          return alert("File saved as " + filename + ".");
        });
      },
      settings: function() {
        dom.shade.show();
        return dom.modal.centre().fadeIn('fast');
      }
    });
  });

}).call(this);
